// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ribdgebybtntpouqfeql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpYmRnZWJ5YnRudHBvdXFmZXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MjIxMDUsImV4cCI6MjA3NDA5ODEwNX0.Eznhctm03Rsoj4eU03DP_4iAxnzAej3lIdglsO7a3zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});